repository_type: pipeline

nf_core_version: 3.1.2

lint: {}

template:
  org: nf-core
  name: annopipeline
  description: assembly and annotation pipeline for bacterial genomes
  author: barbarahelena
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
